### ISSUE TITLE
Not writing multiple sheets 

### ISSUE THREAD

**Issue by sarbashis** [colearendt/xlsx#109]
I am trying to write my data frame into multiple sheets by passing sheet names through a loop. But always found the last value store in the first sheet only. Below is my demo code to reproduce  the result

library(xlsx)
wb <- createWorkbook(type = "xlsx")
tmp <- c("First","Secound","Third")
for (i in length(tmp)) {
  sheetName <- tmp[i]
  NameOfsheet <- createSheet(wb,sheetName = sheetName)
  addDataFrame(1:10,sheet = NameOfsheet)
}
saveWorkbook(wb,file = "test.xlsx")

If I do like
 sheet1 <- createSheet(wb,sheetName = tmp[1])
addDataFrame(1:10,sheet = sheet1)
 
sheet2 <- createSheet(wb,sheetName = tmp[2])
addDataFrame(1:10,sheet = sheet2)

sheet3 <- createSheet(wb,sheetName = tmp[3])
addDataFrame(1:10,sheet = sheet3)

Then I see what I am expecting. 

My xlsx and R version are 
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.13.6

xlsx_0.6.1

**Comment by colearendt** [comment]
Thanks for the report! I am able to reproduce this, but the problem is in your looping structure:

```r
``` r
tmp <- c("First","Secound","Third")
for (i in length(tmp)) {
  print(i)
}
#> [1] 3
```

Created on 2018-09-27 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).


For this and other reasons, `list`s are usually preferred to `loop`s in R. This article seems to have a pretty good overview: https://www.datacamp.com/community/tutorials/tutorial-on-loops-in-r

In any case, logging which iteration you are on works as well! Check out a bit of a different pattern, which accomplishes your goal. (Honestly, the `purrr` package is probably recommended over `mapply`)

``` r
library(xlsx)
wb <- createWorkbook(type = "xlsx")

dfs <- list(
  First = data.frame(1:10),
  Second = data.frame(10:20),
  Third = data.frame(1:100)
)
mapply(function(wb, name, inputdata){
  sh <- createSheet(wb, sheetName = name)
  addDataFrame(inputdata, sheet = sh)
}, wb = list(wb)
, name = names(dfs)
, inputdata = dfs
, SIMPLIFY = FALSE
)
#> [[1]]
#> $ref
#> [1] "Java-Object{org.cran.rexcel.RCellBlock@4a87761d}"
#> 
#> attr(,"class")
#> [1] "CellBlock"
#> 
#> [[2]]
#> $ref
#> [1] "Java-Object{org.cran.rexcel.RCellBlock@66d1af89}"
#> 
#> attr(,"class")
#> [1] "CellBlock"
#> 
#> [[3]]
#> $ref
#> [1] "Java-Object{org.cran.rexcel.RCellBlock@8646db9}"
#> 
#> attr(,"class")
#> [1] "CellBlock"
saveWorkbook(wb,file = "test.xlsx")

blah <- loadWorkbook("test.xlsx")
blah$getNumberOfSheets()
#> [1] 3
```

Created on 2018-09-27 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

(Also, if you do need a loop, better to do something like `for (i in seq_len(length(tmp))) {}`)

**Comment by sarbashis** [comment]
Thank you
