### ISSUE TITLE
skipEmptyRows = FALSE not working

### ISSUE THREAD

**Issue by kiddjmadd** [colearendt/xlsx#77]
Having trouble uploading to github, but up until a recent release, adding the "skipEmptyRows = FALSE" flag would allow all rows in range to be loaded, with empty rows loaded as NA. Now, I'm seeing these rows are skipped even with the flag set to false. Since I can't upload files to github, the CSV exported from excel is below:

//=\\=//=\\=//=\\=//=\\=//=\\=//=\\

A,B,C,D,E,F,G,H,I
12,7,15,7,4,6,5,10,7
11,11,5,4,13,15,9,13,3
12,9,3,8,3,13,3,5,12
8,6,5,14,10,10,9,6,7
5,10,15,11,15,15,6,10,8
11,6,7,4,8,7,8,6,3
,,,,,,,,
9,7,9,6,6,13,4,7,13
7,13,12,8,6,5,5,3,8
13,3,5,3,7,3,14,8,8

//=\\=//=\\=//=\\=//=\\=//=\\=//=\\

R interactive results:

> read.xlsx("test_skip_empty_rows.xlsx", skipEmptyRows = F)
   A  B  C  D  E  F  G  H  I
1 10 11 15  3  3  9 13  9  7
2  6 14 15  5 14  5  9  4  5
3 10  6  8 15  8 11 14 10 10
4 11  5  9 10 10  4 15  6 11
5  3  8  9 10  9 10 14  8  5
6  9 13  3  6 10  7 14  4 14
7 10  9  5 14 14  7 13 13  8
8 12  9 12 10 12 12  7  5  9
9 12 14  3  5  6  6  6 13 13

Session info
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.0.0

loaded via a namespace (and not attached):
[1] tools_3.3.2 Rcpp_0.12.9

//=\\=//=\\=//=\\=//=\\=//=\\=//=\\

Could you check if this is reproducible? 

Best regards,
Jesse Madsen

**Comment by colearendt** [comment]
This does not seem to be advertised behavior of `xlsx::read.xlsx`.  Rather, it seems you are looking for `openxlsx::read.xlsx`.  See the openxlsx documentation here: https://cran.r-project.org/web/packages/openxlsx/openxlsx.pdf 

```
head(openxlsx::read.xlsx)
head(xlsx::read.xlsx)
```

If you do not explicitly choose which to execute, you may have some issues attaching both the xlsx and openxlsx packages (because then order matters).  Use `search()` to see your search path.

A bit confusing that they both use the same method with different arguments - probably for backwards compatibility issues across the packages.

**Comment by kiddjmadd** [comment]
Sorry about that. Closing issue
